// Dados para maquinários (BENS)
export const maquinarios = [
  { id: "29", nome: "Trator 4291 Massey Ferguson", status: "Operacional" },
  { id: "24", nome: "Trator 5078e", status: "Operacional" },
  { id: "25", nome: "Trator 5085e", status: "Operacional" },
  { id: "26", nome: "Trator 5090e", status: "Operacional" },
  { id: "272", nome: "Trator 6125 J Mar - I", status: "Operacional" },
  { id: "3471", nome: "Trator 6125 J N", status: "Operacional" },
  { id: "3472", nome: "Trator 6150 J Tr", status: "Operacional" },
  { id: "13", nome: "Trator 6205 J", status: "Operacional" },
  { id: "3534", nome: "Trator 7200 J Mar I", status: "Operacional" },
  { id: "27", nome: "Trator 7630", status: "Operacional" },
  { id: "263", nome: "Trator Jd 6190 M", status: "Operacional" },
  { id: "63", nome: "Trator Jd 7200 J", status: "Operacional" },
  { id: "367", nome: "Trator Jd 7230 J", status: "Operacional" },
  { id: "3456", nome: "Trator New Holland Tl 580", status: "Operacional" },
]

// Dados para implementos
export const implementos = [
  { id: "193", nome: "02 Micron", status: "Operacional" },
  { id: "30", nome: "Abastecedor de Pulverizador 6500 Mepel", status: "Operacional" },
  { id: "31", nome: "Abastecedor de Pulverizador 6500 Mepel", status: "Operacional" },
  { id: "32", nome: "Abastecedor de Pulverizador 8500 Mepel", status: "Operacional" },
  { id: "3480", nome: "Accura 1600 Kuhn", status: "Operacional" },
  { id: "235", nome: "Adubadeira Distribuidor Semeador Rotax 1300", status: "Operacional" },
  { id: "267", nome: "Adubadeira Esteira Miname", status: "Operacional" },
  { id: "18", nome: "Adubadeira Hennipman ( Verde )", status: "Operacional" },
  { id: "19", nome: "Adubadeira Impacto", status: "Operacional" },
  { id: "3444", nome: "Adubadeira Tatu Terceirizada", status: "Operacional" },
  { id: "3458", nome: "Amostrador de Solo Saci", status: "Operacional" },
  { id: "33", nome: "Arado Aiveca", status: "Operacional" },
  { id: "34", nome: "Arado Aiveca", status: "Operacional" },
  { id: "219", nome: "Arado Aivecas Medio Tatu 1", status: "Operacional" },
  { id: "220", nome: "Arado Aivecas Medio Tatu 2", status: "Operacional" },
  { id: "269", nome: "Arado de Aivecas Medio Reversivel", status: "Operacional" },
  { id: "35", nome: "Arado Pesado 05 Discos Baldan", status: "Operacional" },
  { id: "36", nome: "Arado Pesado 5 Discos Baldan", status: "Operacional" },
  { id: "274", nome: "Arado Subsolador Baldan", status: "Operacional" },
  { id: "3532", nome: "Arrancador e Enleirador de Cebola", status: "Operacional" },
  { id: "243", nome: "Atomizador Costal A Gasolina Matsuyama", status: "Operacional" },
  { id: "323", nome: "Bruttos 12000", status: "Operacional" },
  { id: "3497", nome: "Calcariadeira Lancer ( Terceirizada )", status: "Operacional" },
  { id: "59", nome: "Colhedeira de Alho", status: "Operacional" },
  { id: "60", nome: "Colhedeira de Alho", status: "Operacional" },
  { id: "240", nome: "Colhedeira de Alho Erme", status: "Operacional" },
  { id: "414", nome: "Distribuidor de Adubo ( Jan 10.000 Plus )", status: "Operacional" },
  { id: "424", nome: "Distribuidor de Calcario Accura 1600", status: "Operacional" },
  { id: "436", nome: "Distribuidor de Corretivo ( Benpar Dhc 5000 )", status: "Operacional" },
  { id: "400", nome: "Distribuidor Jan ( Tercerizado )", status: "Operacional" },
  { id: "422", nome: "Embutidora de Grao Ingrain 100 Marcher", status: "Operacional" },
  { id: "102", nome: "Enleiradeira de Cebola", status: "Operacional" },
  { id: "268", nome: "Enxada Rotativa Erp 175b Mec - Rul", status: "Operacional" },
  { id: "40", nome: "Enxadinha Hennipman", status: "Operacional" },
  { id: "423", nome: "Extratora de Graos Outgrain 215 Marcher", status: "Operacional" },
  { id: "393", nome: "Facao 1", status: "Operacional" },
  { id: "394", nome: "Facao 2", status: "Operacional" },
  { id: "41", nome: "Facao Alho", status: "Operacional" },
  { id: "249", nome: "Facao Alho 2 Canteiro", status: "Operacional" },
  { id: "42", nome: "Facao Cebola e Cenoura", status: "Operacional" },
  { id: "385", nome: "Facão em Construção", status: "Operacional" },
  { id: "425", nome: "Grade Aradora Gaicr Tatu", status: "Operacional" },
  { id: "43", nome: "Grade Aradora Intermediaria Tatu", status: "Operacional" },
  { id: "44", nome: "Grade Aradora Pesada Baldan", status: "Operacional" },
  { id: "270", nome: "Grade Intermediaria Baldan Cri 20x28", status: "Operacional" },
  { id: "3474", nome: "Grade Intermediaria Ecoagricola", status: "Operacional" },
  { id: "223", nome: "Grade Niveladora Baldan", status: "Operacional" },
  { id: "336", nome: "Grade Niveladora Monte Alto", status: "Operacional" },
  { id: "3514", nome: "Grade Terceirizada - Marcelino", status: "Operacional" },
  { id: "108", nome: "Guincho 1000 Kg", status: "Operacional" },
  { id: "403", nome: "Guincho Gatg Br 200 Tatu 1034 Kg", status: "Operacional" },
  { id: "183", nome: "Guincho Girafa", status: "Operacional" },
  { id: "246", nome: "Guincho Munk Bag Giratorio Sollus 2.000 Kg", status: "Operacional" },
  { id: "45", nome: "Guincho Traseiro Santa Izabel", status: "Operacional" },
  { id: "372", nome: "Incorporador Defensivos", status: "Operacional" },
  { id: "9", nome: "Indek", status: "Operacional" },
  { id: "1", nome: "Indek - Injeferd Sinba 2d", status: "Operacional" },
  { id: "144", nome: "Indek em Construcao", status: "Operacional" },
  { id: "47", nome: "Lamina Traseira (hidraulico)", status: "Operacional" },
  { id: "405", nome: "Lamina Traseira de Arrasto", status: "Operacional" },
  { id: "387", nome: "Maquina Colhedora e Amarradora de Alho", status: "Operacional" },
  { id: "100", nome: "Marcador Alho 400.000 Plantas", status: "Operacional" },
  { id: "5", nome: "Marcador de Plantio Alho", status: "Operacional" },
  { id: "3557", nome: "Micron Cbt 310-uv8-combat 310 Agt", status: "Operacional" },
  { id: "3489", nome: "Micron Hidraulico 08 Linhas", status: "Operacional" },
  { id: "3490", nome: "Micron Hidraulico 20 Linhas", status: "Operacional" },
  { id: "396", nome: "Micron Ts 650 Hidraulico", status: "Operacional" },
  { id: "326", nome: "Perfurador de Solo Com 2 Brocas", status: "Operacional" },
  { id: "50", nome: "Plaina Baldan", status: "Operacional" },
  { id: "335", nome: "Plaina Eletrica 650w", status: "Operacional" },
  { id: "51", nome: "Plaina Tatu", status: "Operacional" },
  { id: "3485", nome: "Plantadeira Jhon Deere Modelo 2019", status: "Operacional" },
  { id: "3487", nome: "Plantadeira John Deere Modelo 2122", status: "Operacional" },
  { id: "3486", nome: "Plantadeira Jumil 7090 ( Terceirizada )", status: "Operacional" },
  { id: "330", nome: "Plantadeira Semeadora Adub. de Arrasto Vence Tudo", status: "Operacional" },
  { id: "52", nome: "Plantadeira Star Plus", status: "Operacional" },
  { id: "198", nome: "Prancha Imavi", status: "Operacional" },
  { id: "373", nome: "Pre- Misturador", status: "Operacional" },
  { id: "199", nome: "Prensa Hidraulica", status: "Operacional" },
  { id: "333", nome: "Preparadora de Solo c/ Adubadeira - Rotativa Castro", status: "Operacional" },
  { id: "278", nome: "Pulverizador Agricola Condor Am-12", status: "Operacional" },
  { id: "3503", nome: "Pulverizador Columbia Ad-18 Eletrico", status: "Operacional" },
  { id: "99", nome: "Pulverizador Columbia Ad18", status: "Operacional" },
  { id: "20", nome: "Pulverizador Columbia Cross 2000 Lt", status: "Operacional" },
  { id: "53", nome: "Rastel", status: "Operacional" },
  { id: "211", nome: "Retroescavadeira 310 K", status: "Operacional" },
  { id: "54", nome: "Rolo Classificador Alho", status: "Operacional" },
  { id: "3554", nome: "Rolo Compactador Ca 25 Terceirizado", status: "Operacional" },
  { id: "218", nome: "Rolo Faca", status: "Operacional" },
  { id: "324", nome: "Rolo Terceirizado Marcelino Sato", status: "Operacional" },
  { id: "55", nome: "Rotativa Hennipman Verde", status: "Operacional" },
  { id: "14", nome: "Rotativa Hennipman Vermelha", status: "Operacional" },
  { id: "134", nome: "Rotativa Mec Rul", status: "Operacional" },
  { id: "221", nome: "Subsolador de Mola Plana", status: "Operacional" },
  { id: "56", nome: "Subsolador Tatu", status: "Operacional" },
  { id: "302", nome: "Subsolador Tatu 5 Hastes", status: "Operacional" },
  { id: "57", nome: "Suporte Agricola Para Big Bag", status: "Operacional" },
  { id: "404", nome: "Tanque Acton 6.500", status: "Operacional" },
  { id: "264", nome: "Terraceador Tatu", status: "Operacional" },
  { id: "331", nome: "Transpalete 2t R/Ny", status: "Operacional" },
  { id: "222", nome: "Transpaleteira Manual ( Burrinha )", status: "Operacional" },
  { id: "374", nome: "Tratorito Tobata", status: "Operacional" },
  { id: "216", nome: "Tritton 3.600", status: "Operacional" },
  { id: "206", nome: "Uniporte 2030", status: "Operacional" },
  { id: "21", nome: "Uniporte Plus-2000", status: "Operacional" },
  { id: "343", nome: "Uniporte Plus Terceirizado Somar", status: "Operacional" },
  { id: "58", nome: "Vincon - Dist de Adubos", status: "Operacional" },
]
